name: simple_pos
description: Simple offline POS (stok & transaksi) using Flutter + SQLite
publish_to: "none"
version: 0.3.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2
  path_provider: ^2.1.4
  csv: ^6.0.0
  file_picker: ^10.3.3
  shared_preferences: ^2.1.1

  # Untuk printer thermal bluetooth
  blue_thermal_printer: ^1.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
