name: simple_pos
description: Simple offline POS (stok & transaksi) using Flutter + SQLite
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3

flutter:
  uses-material-design: true
